Display subdataset titles instead of their directory names
psychoinformatics-de/sfb1451-projects-catalog pull request #99
Opened 2024-05-15 17:57 UTC by mslw

The subdataset card is modified so that the subdataset title is shown as the card header (the big text linking to the subdataset page), replacing directory name. Sorting is adjusted accordingly, and made case-insensitive.

The directory name is used as the card header if the title is not available, and always shown in small text as "directory".

To achieve this, subdatasets_ready() function is modified to add a display_name property to each subdataset object (similar to what dataset_ready does to the superdataset). The property is needed twice: for sorting (js code) and for display (html template), so it seemed appropriate to add the property instead of having to use the ternary operator twice.

Subdataset sorting uses localeCompare() on the names, which seems to be the recommended method to achieve case-insensitive comparison: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

The fact that we only define the name for available datasets does not seem to be a problem, as the sortedSubdatasets() is called only after filteredSubdatasets() which filters by the available property.

Closes #96

Example:
![image](https://github.com/sfb1451/metadata-catalog/assets/11985212/8413c03b-c28b-4000-adc5-c5258732c58d)

2024-05-16 19:10 UTC, jsheunis commented
I'm currently testing this locally. I haven't looked at the code to see where the issue lies yet, but I've encountered a filtering issue in the subdatasets tab, when filtering by dataset name. The B04 dataset has the name "Behavioural signatures of motor control under uncertainty for different effectors in the healthy young and ageing human brain":

<img width="991" alt="Screenshot 2024-05-16 at 21 04 00" src="https://github.com/sfb1451/metadata-catalog/assets/10141237/e1b3c946-979c-4677-821e-d4cdb25e9666">

But when I try to search according to this name, e.g. typing "beh", there are no results:

<img width="1020" alt="Screenshot 2024-05-16 at 21 07 15" src="https://github.com/sfb1451/metadata-catalog/assets/10141237/2e546455-2d6a-470c-b520-dde3985033ed">

If I search by the directory name though (e.g. typing "B04"), then it works. Will look into the code next.

Another point is that I am in two minds about the display of the "Directory" name. On the one hand it's informative if you know what it's supposed to mean, but on the other hand it can be confusing extra information for someone who doesn't know.

2024-05-16 20:17 UTC, jsheunis commented
The issue is that there's _sorting_, which you updated, and _filtering_, which gave the issues I reported above. To fix filtering, [this line has to be updated](https://github.com/sfb1451/metadata-catalog/pull/99/files#diff-3036cc91f7825279b60d940b375c8c41c27c445a8686e4b271aca086dc7a3650R325):

```javascript
c.dirs_from_path[c.dirs_from_path.length - 1]
   .toLowerCase()
   .indexOf(this.search_text.toLowerCase())
```

should be:

```javascript
c.display_name
   .toLowerCase()
   .indexOf(this.search_text.toLowerCase())
```

2024-05-16 20:20 UTC, jsheunis requested changes
https://github.com/sfb1451/metadata-catalog/pull/99#issuecomment-2116105675

2024-05-16 21:15 UTC, mslw commented
I knew that asking you for a review was a good idea :smile:. Filtering was an omission from my side, will fix tomorrow (I think only by dataset name, not directory, is needed). Thanks!

Comment about the directory name is noted, although I would still lean towards keeping it (if only for my own information on where the things are kept in the superdataset). I'm open to changing it from "directory" to something else (I started with "path" but that is really the last path component).

2024-05-17 14:09 UTC, mslw commented
Made the suggested change and force-pushed without creating a separate commit.

2024-05-17 18:25 UTC, merged